Repository reviewpad/docs, pull requests merged in 2022-09, with the labels that each got.

#35 docs: fix link to built-ins
  docs/getting-started/installation.md
Labels: small

#45 fix: remove reference to $elemContains
  src/built_ins/comments.yml
  src/built_ins/commits.yml
Labels: small

#43 refactor: update label syntax
  docs/guides/syntax.md
Labels: small

#31 refactor: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: small

#41 feat: improve reviewpad.yml
  .github/workflows/reviewpad.yml
  reviewpad.yml
Labels: medium

#48 Updated README.md file
  README.md
Labels: external-contribution

#32 feat: update docusaurus version to 2.1
  docusaurus.config.js
  package.json
Labels: small, ship

#4 switches from typesense search to algolia search
  docusaurus.config.js
  package.json
Labels: external-contribution, ask

#30 docs: add documentation for $hasGitConflicts built-in
  docs/guides/built-ins.mdx
  src/built_ins/hasGitConflicts.yml
  src/built_ins/index.js
Labels: medium, ask

#55 feat: label description update if it exists
  docs/guides/syntax.md
Labels: ask

#58 feat: label pull requests with Git conflicts usecase
  docs/use-cases/label-pull-requests-with-git-conflicts.md
  sidebars.js
Labels: ask

#56 fix: $reviewers built-in returned requested reviewers
  docs/guides/built-ins.mdx
  src/built_ins/reviewers.yml
Labels: ask

#59 feat: $requestedReviewers built-in
  docs/guides/built-ins.mdx
  src/built_ins/index.js
  src/built_ins/requestedReviewers.yml
Labels: ask

#60 feat: $totalCodeReviews documentation
  docs/guides/built-ins.mdx
  src/built_ins/index.js
  src/built_ins/totalCodeReviews.yml
Labels: ask

#61 feat: add v3.7.0 changelog
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v370-faro-edition.md
Labels: ask

#64 feat: add changelog for v3.8.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v380-faro-edition.md
Labels: ask
