Repository reviewpad/docs, pull requests merged in 2022-11, with the labels that each got.

#106 refactor: remove global twitter metatags (title and description)
  docusaurus.config.js
Labels: external-contribution, ask

#91 ops: add deployment github action
  .github/workflows/deploy.yml
Labels: ask

#107 chore: update readme with contact
  README.md
Labels: ship

#108 chore: improve documentation for checker
  RELEASE.md
  scripts/checker.sh
Labels: ship

#105 refactor: improve always-run field definition in the syntax page
  docs/guides/syntax.md
Labels: ask

#104 refactor: align table columns title to the left
  docs/guides/built-ins/actions/addLabel/index.mdx
  docs/guides/built-ins/actions/addToProject/index.mdx
  docs/guides/built-ins/actions/assignAssignees/index.mdx
  docs/guides/built-ins/actions/assignReviewer/index.mdx
  docs/guides/built-ins/actions/assignTeamReviewer/index.mdx
  docs/guides/built-ins/actions/close/index.mdx
  docs/guides/built-ins/actions/comment/index.mdx
  docs/guides/built-ins/actions/commentOnce/index.mdx
  docs/guides/built-ins/actions/disableActions/index.mdx
  docs/guides/built-ins/actions/error/index.mdx
  docs/guides/built-ins/actions/fail/index.mdx
  docs/guides/built-ins/actions/info/index.mdx
  docs/guides/built-ins/actions/merge/index.mdx
  docs/guides/built-ins/actions/removeLabel/index.mdx
  docs/guides/built-ins/actions/removeLabels/index.mdx
  docs/guides/built-ins/actions/review/index.mdx
  docs/guides/built-ins/actions/warn/index.mdx
  docs/guides/built-ins/functions/changed/index.mdx
  docs/guides/built-ins/functions/sprintf/index.mdx
Labels: ask

#100 feat: update close built-in with closure reason
  docs/guides/built-ins/actions/close/example.yml
  docs/guides/built-ins/actions/close/index.mdx
  scripts/checker.sh
Labels: ask

#102 feat: metrics report
  docs/guides/syntax.md
Labels: ask

#109 feat: add changelog for v3.13.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3130-faro-edition.md
Labels: ask

#112 fix: correct spelling error on documentation intro page
  versioned_docs/version-3.13.0/introduction.mdx
Labels: external-contribution, ask

#116 Update contribution document
  versioned_docs/version-3.13.0/contributing/how-to-contribute.md
Labels: external-contribution, ask

#110 chore: remove the deploy section from README
  RELEASE.md
Labels: ask

#118 docs: update pull request count by docs
  docs/guides/built-ins/functions/pullRequestCountBy/index.mdx
  docs/use-cases/automated-labelling/label-based-on-author-groups/example.yml
  docs/use-cases/comment-on-pull-requests/example.yml
  docs/use-cases/reviewer-assignment/assign-senior-reviewers-to-new-joiners/example.yml
  docs/use-cases/ship-show-ask/example.yml
Labels: external-contribution

#120 Update branch organization
  versioned_docs/version-3.13.0/contributing/how-to-contribute.md
Labels: external-contribution, ask

#121 feat: checkRunConclusion builtin
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/checkRunConclusion/example.yml
  docs/guides/built-ins/functions/checkRunConclusion/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: ask

#124 feat: state built-in
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/state/example.yml
  docs/guides/built-ins/functions/state/index.mdx
Labels: show
