Repository reviewpad/docs, pull requests merged in 2022-12, with the labels that each got.

#127 docs: have all checks run completed
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/haveAllChecksRunCompleted/example.yml
  docs/guides/built-ins/functions/haveAllChecksRunCompleted/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: external-contribution, ask

#126 docs: add documentation for hasBinaryFile built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/hasBinaryFile/example.yml
  docs/guides/built-ins/functions/hasBinaryFile/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: external-contribution, ask

#129 feat: isLinkedToProject built-in
  docs/guides/built-ins/actions/addToProject/index.mdx
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/isLinkedToProject/example.yml
  docs/guides/built-ins/functions/isLinkedToProject/index.mdx
Labels: ask

#128 feat: add use case for issue management in projects
  docs/use-cases/manage-issues-projects/example.yml
  docs/use-cases/manage-issues-projects/index.mdx
  sidebars.js
Labels: ask

#125 docs: changelog v3.16.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3160.md
Labels: ask

#140 feat: docs for extends
  docs/guides/extends.md
  docs/guides/syntax.md
  sidebars.js
Labels: show

#141 docs: changelog v3.17.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3170.md
Labels: ask

#142 feat: blocking merge use case
  docs/guides/built-ins/actions/fail/index.mdx
  docs/use-cases/blocking-merge/example.yml
  docs/use-cases/blocking-merge/index.mdx
  sidebars.js
  static/img/blocking-merge/configure-status-check.png
  static/img/blocking-merge/merge-blocked.png
Labels: external-contribution, ask

#146 feat: reports guide
  docs/guides/reports/index.mdx
  docs/guides/reports/stale.yml
  docs/guides/reports/verbose.yml
  sidebars.js
  static/img/reports/executed_actions.png
  static/img/reports/info.png
  static/img/reports/metrics.png
Labels: external-contribution, ask

#147 docs: add approvalsCount built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/approvalsCount/example.yml
  docs/guides/built-ins/functions/approvalsCount/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: external-contribution, ask

#145 feat: update merge action default behaviour
  docs/guides/built-ins/actions/merge/index.mdx
Labels: ask

#149 feat: metrics-on-merge property
  docs/guides/extends.md
  docs/guides/reports/index.mdx
  docs/guides/syntax.md
Labels: ask

#150 docs: add eventType built-in
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/eventType/example.yml
  docs/guides/built-ins/functions/eventType/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: show

#151 docs: add triggerWorkflow built-in
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/actions/triggerWorkflow/example.yml
  docs/guides/built-ins/actions/triggerWorkflow/index.mdx
  docs/guides/built-ins/built-ins.mdx
Labels: show

#154 Fix/metrics report typos
  docs/guides/reports/index.mdx
  versioned_docs/version-3.18.0/guides/reports/index.mdx
Labels: external-contribution, ask

#153 docs: add docs for filesPath built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/filesPath/example.yml
  docs/guides/built-ins/functions/filesPath/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: external-contribution, ask

#152 docs: add join built-in
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/join/example.yml
  docs/guides/built-ins/functions/join/index.mdx
Labels: external-contribution, ask

#157 docs: context built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/context/example.yml
  docs/guides/built-ins/functions/context/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: ask

#158 docs: toJSON built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/toJSON/example.yml
  docs/guides/built-ins/functions/toJSON/index.mdx
Labels: ask

#159 docs: selectFromJSON built-in
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/selectFromJSON/example.yml
  docs/guides/built-ins/functions/selectFromJSON/index.mdx
Labels: ask

#156 docs: matchString built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/matchString/example.yml
  docs/guides/built-ins/functions/matchString/index.mdx
Labels: external-contribution, ask

#161 docs: add info for setProjectField
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/actions/setProjectField/example.yml
  docs/guides/built-ins/actions/setProjectField/index.mdx
  docs/guides/built-ins/built-ins.mdx
Labels: ask

#155 docs: changelog v3.19.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3190.md
Labels: ask

#163 docs: toNumber built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/toNumber/example.yml
  docs/guides/built-ins/functions/toNumber/index.mdx
Labels: ask

#164 docs: toBool built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/toBool/example.yml
  docs/guides/built-ins/functions/toBool/index.mdx
Labels: ask

#165 docs: toStringArray built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/toStringArray/example.yml
  docs/guides/built-ins/functions/toStringArray/index.mdx
Labels: ask

#166 docs: changelog v3.20.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3200.md
Labels: show
