Repository reviewpad/docs, pull requests merged in 2023-03, with the labels that each got.

#211 chore: update copyright
  docusaurus.config.js
Labels: small, large, ask

#214 fix: discord link
  docusaurus.config.js
Labels: small, large, ask, waiting-review

#216 docs: add documentation for remove from project
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/actions/removeFromProject/example.yml
  docs/guides/built-ins/actions/removeFromProject/index.mdx
  docs/guides/built-ins/built-ins.mdx
Labels: medium, new-feature, waiting-review

#218 feat: changelog v4.0.0
  src/pages/changelog/index.mdx
  src/pages/changelog/v4.0.0.md
Labels: small

#221 fix: test reviewpad configurations inconsistencies
  RELEASE.md
  docs/guides/built-ins/actions/assignCodeAuthorReviewers/example.yml
  scripts/checker.sh
Labels: small, bug-fix

#230 feat: update assignAssignees docs
  docs/guides/built-ins/actions/assignAssignees/example.yml
  docs/guides/built-ins/actions/assignAssignees/index.mdx
Labels: small, new-feature

#229 docs: add documentation for hasAnyCheckRunCompleted built-in function
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/hasAnyCheckRunCompleted/example.yml
  docs/guides/built-ins/functions/hasAnyCheckRunCompleted/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: medium, ask

#234 fix: replace spec by where in group syntax
  docs/guides/syntax.md
Labels: small

#232 docs: remove api-version from syntax page
  docs/guides/syntax.md
  versioned_docs/version-v4/guides/syntax.md
Labels: small, ask, improvements

#236 feat: document playground sharable link
  docs/getting-started/playground.mdx
  static/img/playground-preview.png
Labels: small

#239 feat: changelog v4.2.0
  src/pages/changelog/index.mdx
  src/pages/changelog/v4.2.0.md
Labels: small, ship, improvements

#245 feat: reviewpad summarize command
  docs/guides/commands/commands.mdx
  docs/guides/commands/index.js
  docs/guides/commands/summarize.mdx
Labels: medium, ask, new-feature

#260 feat: add changelog v4.4.0
  src/pages/changelog/index.mdx
  src/pages/changelog/v4.4.0.md
Labels: small, ship, improvements
