Repository reviewpad/docs, pull requests merged in 2023-02, with the labels that each got.

#183 feat: changelog for the v3.23.0 release
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3230.md
Labels: small, ask

#186 fix: fix typos
  docs/use-cases/blocking-merge/index.mdx
  docs/use-cases/enforce-conventional-commits/index.mdx
Labels: small, external-contribution, ship

#190 feat: update docs
  babel.config.js
  docs/guides/built-ins/actions/comment/index.mdx
  docs/guides/built-ins/actions/disableMerge/example.yml
  docs/guides/built-ins/actions/disableMerge/index.mdx
  docs/guides/built-ins/actions/fail/index.mdx
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/actions/rebase/index.mdx
  docs/guides/built-ins/actions/triggerWorkflow/index.mdx
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/approvalsCount/index.mdx
  docs/guides/built-ins/functions/eventType/index.mdx
  docs/guides/built-ins/functions/isBinary/index.mdx
  docs/guides/built-ins/functions/totalCreatedPullRequests/index.mdx
  docs/use-cases/blocking-merge/example.yml
  docs/use-cases/blocking-merge/index.mdx
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v230.md
  src/pages/changelog/reviewpad-v3240.md
  static/img/blocking-merge/configure-status-check.png
  static/img/blocking-merge/merge-blocked.png
Labels: large, ask

#193 feat: approve built-in
  docs/guides/built-ins/actions/approve/example.yml
  docs/guides/built-ins/actions/approve/index.mdx
  docs/guides/built-ins/actions/fail/index.mdx
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/actions/review/index.mdx
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/totalCreatedPullRequests/index.mdx
Labels: medium, ask

#194 docs: adds documentation for assign code author reviewer
  docs/guides/built-ins/actions/assignCodeAuthorReviewers/example.yml
  docs/guides/built-ins/actions/assignCodeAuthorReviewers/index.mdx
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/built-ins.mdx
Labels: medium, ask

#195 feat: changelog for v3.25.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3250.md
Labels: small, show

#199 feat: remove disableMerge
  docs/guides/built-ins/actions/disableMerge/example.yml
  docs/guides/built-ins/actions/disableMerge/index.mdx
  docs/guides/built-ins/actions/fail/index.mdx
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/built-ins.mdx
  docs/use-cases/blocking-merge/index.mdx
  src/pages/changelog/reviewpad-v230.md
  static/img/blocking-merge/configure-status-check.png
  static/img/blocking-merge/merge-blocked.png
Labels: medium, ask

#200 feat: add changelog for v3.26.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3260.md
Labels: small, ship

#201 docs: add documentation for is updated with base branch built in
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/isUpdatedWithBaseBranch/example.yml
  docs/guides/built-ins/functions/isUpdatedWithBaseBranch/index.mdx
Labels: medium, ask

#202 docs: update have all checks run completed with third parameter
  docs/guides/built-ins/functions/haveAllChecksRunCompleted/example.yml
  docs/guides/built-ins/functions/haveAllChecksRunCompleted/index.mdx
Labels: small, ask

#206 chore: remove references to the GitHub Action
  docs/common-pitfalls.mdx
  docs/getting-started/installation.mdx
  docs/guides/built-ins/actions/rebase/index.mdx
  docs/guides/built-ins/actions/triggerWorkflow/index.mdx
  docs/guides/built-ins/functions/team/index.mdx
  docs/guides/migrations.mdx
  sidebars.js
Labels: large, ask

#207 chore: add GitHub Action deprecation banner
  docs/getting-started/installation-action-tokenized.mdx
  docs/getting-started/installation-action.mdx
Labels: small, ask

#210 feat: add github icon to header and update repo link
  docusaurus.config.js
  src/styles/global.css
  static/img/discord-brand-dark.svg
  static/img/discord-brand.svg
  static/img/github-brand-dark.svg
  static/img/github-brand.svg
  static/img/twitter-brand-dark.svg
  static/img/twitter-brand.svg
Labels: small, large, ask
