Repository reviewpad/docs, pull requests merged in 2023-05, with the labels that each got.

#282 docs: update assign-reviewers command
  docs/guides/commands/assign-reviewers.mdx
  docs/guides/commands/commands.mdx
Labels: medium, ask, breaking-change, waiting-review

#283 feat: add changelog for v4.8.0
  src/pages/changelog/index.mdx
  src/pages/changelog/v4.8.0.md
Labels: small, ship

#285 fix: remove the outdated section in the assignCodeAuthorReviewers built-in documentation
  docs/guides/built-ins/actions/assignCodeAuthorReviewers/index.mdx
Labels: small, ship

#286 feat: add changelog v4.9.0
  src/pages/changelog/index.mdx
  src/pages/changelog/v4.9.0.md
Labels: small, ship

#288 docs: failCheckStatus built-in
  docs/guides/built-ins/actions/failCheckStatus/example.yml
  docs/guides/built-ins/actions/failCheckStatus/index.mdx
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/built-ins.mdx
  yarn.lock
Labels: large, ask, waiting-approval, requires-author-attention

#292 feat: remove the version selector from the top nativation bar
  docusaurus.config.js
Labels: small, show

#294 feat: remove the changelog link from the top navigation bar
  docusaurus.config.js
Labels: ship
