Repository reviewpad/docs, pull requests merged in 2023-01, with the labels that each got.

#168 docs: changelog v3.21.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3210.md
Labels: show

#171 feat: introduce commands page
  docs/guides/commands/assign-reviewers.mdx
  docs/guides/commands/commands.mdx
  docs/guides/commands/index.js
  sidebars.js
Labels: medium, ask

#173 feat: assign random reviewer cmd
  docs/guides/commands/assign-random-reviewer.mdx
  docs/guides/commands/commands.mdx
  docs/guides/commands/index.js
Labels: small, ask

#170 feat: changelog v3.22.0
  src/pages/changelog/index.mdx
  src/pages/changelog/reviewpad-v3220.md
Labels: small, ask

#176 fix: typo in triggerWorkflow built-in
  docs/guides/built-ins/actions/triggerWorkflow/index.mdx
Labels: small, ship

#177 fix: wrong arg built-in example
  docs/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.12.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.13.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.14.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.15.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.16.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.17.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.18.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.19.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.20.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.21.0/guides/built-ins/actions/review/example.yml
  versioned_docs/version-3.22.0/guides/built-ins/actions/review/example.yml
Labels: small, ask

#178 fix: comment built-in example
  docs/guides/built-ins/actions/comment/example.yml
  versioned_docs/version-3.16.0/guides/built-ins/actions/comment/example.yml
  versioned_docs/version-3.17.0/guides/built-ins/actions/comment/example.yml
  versioned_docs/version-3.18.0/guides/built-ins/actions/comment/example.yml
  versioned_docs/version-3.19.0/guides/built-ins/actions/comment/example.yml
  versioned_docs/version-3.20.0/guides/built-ins/actions/comment/example.yml
  versioned_docs/version-3.21.0/guides/built-ins/actions/comment/example.yml
  versioned_docs/version-3.22.0/guides/built-ins/actions/comment/example.yml
Labels: small, ask

#180 docs: rebase built-in
  docs/guides/built-ins/actions/index.js
  docs/guides/built-ins/actions/rebase/example.yml
  docs/guides/built-ins/actions/rebase/index.mdx
  docs/guides/built-ins/built-ins.mdx
Labels: medium, ask

#184 feat: dry-run cmd docs
  docs/guides/commands/commands.mdx
  docs/guides/commands/dry-run.mdx
  docs/guides/commands/index.js
Labels: small, ask

#185 feat: document tracking overrides with logs
  docs/guides/extends/index.mdx
Labels: small, ask
