Repository reviewpad/docs, pull requests merged in 2023-04, with the labels that each got.

#271 docs: built-in extractMarkdownHeadingContent
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/extractMarkdownHeadingContent/example.yml
  docs/guides/built-ins/functions/extractMarkdownHeadingContent/index.mdx
  docs/guides/built-ins/functions/index.js
Labels: medium, ask, new-feature

#270 docs: built-in subStringMatches
  docs/guides/built-ins/built-ins.mdx
  docs/guides/built-ins/functions/index.js
  docs/guides/built-ins/functions/subMatchesString/example.yml
  docs/guides/built-ins/functions/subMatchesString/index.mdx
Labels: medium, ask, new-feature, waiting-review

#274 feat: changelog v4.6.0
  src/pages/changelog/v4.5.0.md
  src/pages/changelog/v4.6.0.md
Labels: medium, ship, improvements

#275 feat: add changelog for v4.7.0
  src/pages/changelog/index.mdx
  src/pages/changelog/v4.7.0.md
Labels: medium, show, improvements

#280 docs: remove always run property
  docs/getting-started/onboarding-configuration.yml
  docs/guides/built-ins/actions/assignAssignees/example.yml
  docs/guides/extends/common.yml
  docs/guides/extends/reviewpad.yml
  docs/guides/extends/reviewpad_final.yml
  docs/guides/extends/team_a.yml
  docs/guides/reports/verbose.yml
  docs/guides/semantics.md
  docs/guides/syntax.md
  docs/use-cases/enforce-branch-conventions/example.yml
Labels: large, ask, improvements, approved
